### PR TITLE
Updated Whole to do list

### PR DESCRIPTION
**Pull request by amanjagdev**
Screenshot 2020-10-01 175645
Screenshot 2020-10-01 175701
This is how the new to-do list looks
And the edit button also works :)

Hope you will like it

### CODE REVIEW

**Comment by dahiya-code** [comment]
Well must say pretty good job...being still a beginner I will definitely learn a lot from your code

**Comment by amanjagdev** [comment]
@navya252001 Happy to help.

There is one request, you need to add "hacktoberfest" topic in your repository in order for this PR to count in hactoberfest.
Please do the needful regarding this

**Comment by dahiya-code** [comment]
Added it

**Comment by amanjagdev** [comment]
@navya252001 Thank you but there is a slight problem, you need to add label "hacktoberfest-accepted" in the PR Labels where you added "hacktoberfest".
And you need to add "hacktoberfest" in the topics of your repository like mentioned in the below example
image

You can refer this to do so
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics

Please take a look at this,
Thank you

**Comment by dahiya-code** [comment]
I am still learning about how github works. Now is it fine?

**Pull request merged**
